### ISSUE TITLE
Include Flathub images inside this repository

### ISSUE THREAD

**Issue by Eonfge** [flathub/io.conduktor.Conduktor#30]
Upstream changed the way how they deal with images. There is now a CDN in front of it so our image links break with an update. Better include some images in this repository directly.

---

@sderosiaux Hey, could you provide us with some (links to) high quality images for your product? Also, ever thought about changing the store text?

You have about 1400 downloads from Flathub btw, so that's not bad ;)
https://klausenbusk.github.io/flathub-stats/#ref=io.conduktor.Conduktor&interval=infinity&downloadType=installs%2Bupdates

**Comment by sderosiaux** [comment]
Nice! I'll keep that link :)
about the text and pictures (and version), can we change anything in here and that will automatically be rebuilt?

I saw you updated some pictures, indeed, we have rewritten our website, and a new version again is coming in a few days. Our new logo https://staging.conduktor.io/images/conduktor-square-bg.png

**Comment by Eonfge** [comment]
> about the text and pictures (and version), can we change anything in here and that will automatically be rebuilt?

If you check-out this repository and make another branch, you can edit whatever you want. After that, you can create a merge-request with master and when all checks pass, you can merge it. Then it's simply a matter of clicking publish at [/builds](https://flathub.org/builds/#/). Users have their local cache but that should refresh within 24 hours.

I'll start a new branch for the logo. Feel free to make commits to change the page text.

**Comment by Eonfge** [comment]
@sderosiaux  origin/rebranding now has the new logo prepared. Feel free to make other changes related to the text

**Comment by sderosiaux** [comment]
got it, thanks @Eonfge
