### ISSUE TITLE
Error: Wrong size for extra data https://releases.conduktor.io/linux-zip

### ISSUE THREAD

**Issue by sebasmagri** [flathub/io.conduktor.Conduktor#58]

**Comment by Eonfge** [comment]
I have a problem reproducing this issue, if I download `Conduktor-linux-2.21.7.zip` from their website, I get the following hash and file size:

```
[kevin@kevin-fedora-desktop ~/Downloads]$ sha256sum ./Conduktor-linux-2.21.7.zip 
c686bcb7324275baa0a3940b2c3d4c1b33330a5cd83ff77d569b6252b4bf730b  ./Conduktor-linux-2.21.7.zip
```

```
[kevin@kevin-fedora-desktop ~/Downloads]$ ls -al
total 3198220
drwxr-xr-x. 1 kevin kevin       1506  9 mei 17:01  .
drwx------. 1 kevin kevin        590  9 mei 16:48  ..
-rw-r--r--. 1 kevin kevin  246502618  9 mei 16:53  Conduktor-linux-2.21.7.zip
```

Could you try again tomorrow? I know it sounds a bit weird but we sometimes have some desyncs with upstream?

**Comment by Eonfge** [comment]
I'm closing this issue for now. Seems that Upstream made a release and then withdrew it. We're discussing a better way of distributing in the future.
