### ISSUE TITLE
Verify app

### ISSUE THREAD

**Issue by Eonfge** [flathub/io.conduktor.Conduktor#83]
@sderosiaux Flathub has been updated with a lot of functionality. One of these changes, is that you can now Verify your app!

How to:
- Log in to Flathub with the Github account that has maintainer rights on this repository: https://flathub.org/en-GB/login
- Go to Conduktor and than Developer Settings
- Create a page at https://conduktor.io/.well-known/org.flathub.VerifiedApps.txt with the right UUID
- Proceed with wizzard

Once completed, Conduktor will get the Magical Blue Check-mark™ !

**Comment by sderosiaux** [comment]
Thanks, will do!
